name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Environment Variables
      run: |
        if [ -z "${{ secrets.GOOGLE_API_KEY }}" ]; then
          echo "Error: GOOGLE_API_KEY is not set!"
          exit 1
        fi
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > /home/ubuntu/ATS-Resume-Expert/app/.env
        cat /home/ubuntu/ATS-Resume-Expert/app/.env

    - name: Deploy to EC2 if changes detected
      run: |
        echo "Deploying to EC2..."
        cd ~/ATS-Resume-Expert
        git pull origin main
        docker-compose pull
        docker-compose down
        docker-compose up -d --build
        docker system prune -f
