name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: self-hosted  # Run on your EC2 instance (self-hosted runner)

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose

    - name: SSH to EC2 and Deploy
      run: |
        # Pull the latest code and images
        cd ~/deploy
        git pull origin main
        docker-compose pull
        docker-compose down
        docker-compose up -d --build
        docker system prune -f
