name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

      - name: Check for changes
      id: check_changes
      run: |
        git fetch origin main
        CHANGES=$(git diff --name-only ${{ github.sha }} origin/main)
        # Check for changes in both main app files and nginx.conf
        if echo "$CHANGES" | grep -q "nginx/nginx.conf"; then
          CHANGES="$CHANGES nginx/nginx.conf"
        fi
        echo "::set-output name=changes::$CHANGES"

    - name: Set Environment Variables
      run: |
        if [ -z "${{ secrets.GOOGLE_API_KEY }}" ]; then
          echo "Error: GOOGLE_API_KEY is not set!"
          exit 1
        fi
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > /home/ubuntu/ATS-Resume-Expert/app/.env
        cat /home/ubuntu/ATS-Resume-Expert/app/.env

    - name: Notify if No Changes Detected
      if: steps.check_changes.outputs.changes == ''
      run: echo "No changes detected, skipping deployment."

    - name: Deploy to EC2 if changes detected
      # if: steps.check_changes.outputs.changes != ''
      run: |
        echo "Deploying to EC2..."
        cd ~/ATS-Resume-Expert
        git pull origin main
        docker-compose pull
        docker-compose down
        docker-compose up -d --build
        docker system prune -f
